//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DragNoteApp.DragNote
{

    public partial class Event : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        string fname;
        [Size(50)]
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>("name", ref fname, value); }
        }
        DateTime fstart_time;
        public DateTime start_time
        {
            get { return fstart_time; }
            set { SetPropertyValue<DateTime>("start_time", ref fstart_time, value); }
        }
        DateTime fend_time;
        public DateTime end_time
        {
            get { return fend_time; }
            set { SetPropertyValue<DateTime>("end_time", ref fend_time, value); }
        }
        [Association(@"RaceReferencesEvent", typeof(Race))]
        public XPCollection<Race> Races { get { return GetCollection<Race>("Races"); } }
    }

}
