//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace DragNoteApp.DragNote
{

    public partial class Race : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>("id", ref fid, value); }
        }
        Driver fid_driver;
        [Association(@"RaceReferencesDriver")]
        public Driver id_driver
        {
            get { return fid_driver; }
            set { SetPropertyValue<Driver>("id_driver", ref fid_driver, value); }
        }
        Event fid_event;
        [Association(@"RaceReferencesEvent")]
        public Event id_event
        {
            get { return fid_event; }
            set { SetPropertyValue<Event>("id_event", ref fid_event, value); }
        }
        double frace_time;
        public double race_time
        {
            get { return frace_time; }
            set { SetPropertyValue<double>("race_time", ref frace_time, value); }
        }
        double fet;
        public double et
        {
            get { return fet; }
            set { SetPropertyValue<double>("et", ref fet, value); }
        }
        double frt;
        public double rt
        {
            get { return frt; }
            set { SetPropertyValue<double>("rt", ref frt, value); }
        }
        double fet_rt;
        public double et_rt
        {
            get { return fet_rt; }
            set { SetPropertyValue<double>("et_rt", ref fet_rt, value); }
        }
    }

}
